version: '3.8'

services:
  web:
    build: .  # This tells Docker to build the image using the Dockerfile in the current directory
    container_name: personal_portfolio
    ports:
      - "80:80"  # Maps port 80 on the host to port 80 in the container
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge


